languageCode = "en-us"
title = "Apollo Group Site"
baseurl = "https://stride-apollo.github.io/"
theme = "prologue_mod"
publishDir = "."

[params]
  name = "Apollo"
  description = "blabla"


[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "#"

