languageCode = "en-us"
title = "Apollo Group Site"
baseurl = "https://stride-apollo.github.io/"
theme = "prologue_mod"
publishDir = "."

[params]
name = "Apollo"
description = "Group for Bachelor Thesis"


[[params.social]]
medium = "github"
icon = "github"
link = "https://github.com/Stride-Apollo"

[[params.social]]
medium = "email"
icon = "envelope"
link = "mailto:stijn.janssens@student.uantwerpen.be"

# Portfolio column one

[[params.authors]]
title = "Anthony Hermans"
alt = ""
source = "/img/anthony.jpg"
url = "#"
description = """
Blablabla <br/>
dit is text <br/>
meer text <br/>
"""

[[params.authors]]
title = "Stijn Janssens"
alt = ""
source = "/img/stijn.jpg"
url = "#"
description = """
Fan of Artificial Intelligence and Big Data. Some of my favorite previous projects are [Helix](https://github.com/evertheylen/TA_TO) and [OverWatch](https://github.com/evertheylen/SmartHome).
Hobby is playing music: drums, percussion and electric guitar.
"""

[[params.authors]]
title = "Federico Quin"
alt = ""
source = "/img/federico.jpg"
url = "#"
description = """
Student Number: 20140938<br/>
Birth Date: 17/07/1995<br/>
Role: (still undecided)<br/>
"""

[[params.authors]]
title = "Sam Mylle"
alt = ""
source = "/img/sam.jpg"
url = "#"
description = """
Student Number: 20142520<br/>
Birth Date: 29/09/1996<br/>
Role: Website maintenance<br/>
"""

[[params.authors]]
title = "Evert Heylen"
alt = ""
source = "/img/evert.jpg"
url = "#"
description = """
Fan of Python and Arch Linux, and open source software in general. Some of my favorite projects are [Helix](https://github.com/evertheylen/TA_TO) and [Sparrow](https://github.com/evertheylen/Sparrow). Hobbies include hiking and stage lighting.
"""
